<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="syn_table" >

  <xacro:arg name="floating_table" default="false" />

  <xacro:property name="roomheight" value="3.0" />
  <xacro:property name="tableheight" value="0.86" />
  <xacro:property name="tablewidth" value="0.61" />
  <xacro:property name="tabledepth" value="0.9" />
  <xacro:property name="ur10_mount_height" value="0.01" />
  <xacro:property name="ur10_mount_width" value="0.2" />
  <xacro:property name="ur10_mount_depth" value="0.2" />
  <xacro:property name="scan_offset_x" value="0.00" />
  <xacro:property name="scan_offset_y" value="-0.32" />
  <xacro:property name="scan_offset_z" value="0.03" />

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="brown">
    <color rgba="0.87 0.72 0.53 1"/>
  </material>
  <material name="lightgray">
    <color rgba="0.6 0.6 0.6 1"/>
  </material>

  <link name="floor">
    <inertial>
      <origin xyz="0.0 0.0 0.0" />
      <mass value="2000" />
      <inertia  ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <material name="black" />
      <origin xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="5.0 5.0 0.001" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" />
      <geometry>
      <box size="8.0 8.0 0.001" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="floor">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
    <!-- kp: stiffness kd: damping mu1, mu2: friction -->
    <mu1>100.0</mu1>
    <mu2>100.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <link name="table">
    <inertial>
      <origin xyz="0 0 ${tableheight/2}" />
      <mass value="10" />
      <inertia  ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <material name="brown" />
      <origin xyz="0.0 0.0 ${tableheight/2}" />
      <geometry>
        <box size="${tablewidth} ${tabledepth} ${tableheight}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 ${tableheight/2}" />
      <geometry>
        <box size="${tablewidth} ${tabledepth} ${tableheight}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="table">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
    <mu1>100.0</mu1>
    <mu2>100.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <link name="table_top"/>

  <link name="scan"/>

  <link name="ur10_mount">
    <inertial>
      <origin xyz="0 0 ${ur10_mount_height/2}" />
      <mass value="2000" />
      <inertia  ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <material name="lightgray" />
      <origin xyz="0.0 0.0 ${ur10_mount_height/2}" />
      <geometry>
        <box size="${ur10_mount_width} ${ur10_mount_depth} ${ur10_mount_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 ${ur10_mount_height/2}" />
      <geometry>
        <box size="${ur10_mount_width} ${ur10_mount_depth} ${ur10_mount_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="ur10_mount">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
    <mu1>100.0</mu1>
    <mu2>100.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <joint name="floor_table_joint" type="fixed">
    <parent link="floor"/>
    <child link="table"/>
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>

  <joint name="table_mount_joint" type="fixed">
    <parent link="table"/>
    <child link="ur10_mount"/>
	  <origin xyz="0 -0.16 ${tableheight}" rpy="0 0 0" />
  </joint>

  <joint name="table_top_joint" type="fixed">
    <parent link="table"/>
    <child link="table_top"/>
	  <origin xyz="0 0 ${tableheight}" rpy="0 0 0" />
  </joint>

  <joint name="mount_scan_joint" type="fixed">
    <parent link="ur10_mount"/>
    <child link="scan"/>
	  <origin xyz="${scan_offset_x} ${scan_offset_y} ${scan_offset_z}" rpy="0 0 0" />
  </joint>

</robot>
