trackers:
  - id: 1
    type: "rigid"
    name: "calibobj"
    markers:
      - {id: 32, name: "origin_marker", options: "pos=3.5,3.0,3.0"}
      - {id: 33, name: "x_axis_marker", options: "pos=268.951,3.0,3.0"}
      - {id: 34, name: "aux1_marker", options: "pos=269.188,199.116,0.58"}
      - {id: 35, name: "aux2_marker", options: "pos=233.578,235.966,0.0"}
      - {id: 36, name: "y_axis_marker", options: "pos=7.356,234.888,3.0"}
  - id: 2
    type: "rigid"
    name: "stylus"
    markers:
      - {id: 24, name: "small_ring_0", options: "pos=-18.1908,0,-21.9"}
      - {id: 25, name: "small_ring_1", options: "pos=-0.89953,-17.7921,-21.6836"}
      - {id: 26, name: "small_ring_2", options: "pos=18.1908,0,-21.9"}
      - {id: 27, name: "small_ring_3", options: "pos=0.807593,18.0228,-21.6836"}
      - {id: 28, name: "large_ring_4", options: "pos=0.801741,46.7872,-156.977"}
      - {id: 29, name: "large_ring_5", options: "pos=38.811,4.67253,-158.76"}
      - {id: 30, name: "large_ring_6", options: "pos=-5.01625,-32.4563,-160.765"}
      - {id: 31, name: "large_ring_7", options: "pos=-40.3851,7.3563,-161.57"}
  - id: 3
    type: "rigid"
    name: "shadowcan"
    markers:
      - {id: 40, name: "top_marker_0", options: "pos=13.9753,-13.9753,0"}
      - {id: 41, name: "top_marker_1", options: "pos=14.1353,14.0428,0.0641818"}
      - {id: 42, name: "top_marker_2", options: "pos=-13.9753,13.9753,0"}
      - {id: 43, name: "top_marker_3", options: "pos=-14.1521,-14.3992,0.0641818"}
  - id: 4
    type: "rigid"
    name: "bottle"
    markers:
      - {id: 50, name: "top_ring_0", options: "pos=43.6013,0,-111"}
      - {id: 51, name: "top_ring_1", options: "pos=-1.21136,43.0428,-110.861"}
      - {id: 52, name: "top_ring_2", options: "pos=1.04894,-44.6032,-110.861"}
      - {id: 53, name: "top_ring_3", options: "pos=-43.6013,0,-111"}
      - {id: 54, name: "bottom_ring_4", options: "pos=42.0788,0.0207356,-259.261"}
      - {id: 55, name: "bottom_ring_5", options: "pos=-0.296168,-42.8979,-260.63"}
      - {id: 56, name: "bottom_ring_6", options: "pos=-2.85987,42.2863,-259.479"}
      - {id: 57, name: "bottom_ring_7", options: "pos=-43.5367,1.13893,-259.612"}
