controller_list:
  - name: fake_manipulator_controller
    joints:
      - ur10_shoulder_pan_joint
      - ur10_shoulder_lift_joint
      - ur10_elbow_joint
      - ur10_wrist_1_joint
      - ur10_wrist_2_joint
      - ur10_wrist_3_joint
  - name: fake_endeffector_controller
    joints:
      []
